#!/bin/python3

from grading import graders

problem_id = '008-vector'
test_cases = [('2.in', '2.out'), ('1.in', '1.out'), ('3.in', '3.out')]
options = {'output_diff_for': ['1.in'], 'diff_max_lines': 100, 'treat_non_zero_as_runtime_error': False, 'diff_context_lines': 3}
weights = [1.0, 1.0, 1.0]

graders.handle_problem_action(problem_id, test_cases, options=options, weights=weights)
